### ISSUE TITLE
JBNU compile Error: GAZEBO

### ISSUE THREAD

**Issue by Ryuha96** [kestr31/px4-container#29]
simulator@simulator-MS-7C94:~$ docker run -it --rm \
>    -e DISPLAY=$DISPLAY \
>    -e QT_NO_MITSHM=1 \
>    -e XDG_RUNTIME_DIR=/tmp \
>    -v /tmp/.X11-unix:/tmp/.X11-unix \
>    --net host \
>    --device=/dev/dri:/dev/dri \
>    --gpus all \
>    --privileged \
>    kestr3l/px4:gazebo-gpu-0.0.2

/usr/local/bin/entrypoint.sh: line 40: [: missing `]'
HEADLESS is : Not 1, Running Gazebo SITL in normal mode
make: Entering directory '/root/PX4-Autopilot'
[0/11] git submodule Tools/sitl_gazebo
[6/11] Performing configure step for 'sitl_gazebo'
-- install-prefix: /usr/local
-- cmake build type: RelWithDebInfo
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/lib/ccache/cc
-- Check for working C compiler: /usr/lib/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/ccache/c++
-- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX17
-- Performing Test COMPILER_SUPPORTS_CXX17 - Success
-- Performing Test COMPILER_SUPPORTS_CXX14
-- Performing Test COMPILER_SUPPORTS_CXX14 - Success
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Using C++17 standard
-- ccache enabled via symlink (/usr/lib/ccache/c++ -> /usr/bin/ccache)
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.58") found components: system thread filesystem 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'bullet>=2.82'
--   Found bullet, version 2.88
-- Found ccd: /usr/include (found suitable version "2.0", minimum required is "2.0") 
-- Found fcl: /usr/include (found suitable version "0.5.0", minimum required is "0.3.2") 
-- Found assimp: /usr/include (found version "5.0.0") 
-- Found DART: /usr/include (Required is at least version "6.6") found components: dart 
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.40.0") found components: thread system filesystem program_options regex iostreams date_time 
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.6.1") 
-- Looking for ignition-math6 -- found version 6.10.0
-- Searching for dependencies of ignition-math6
-- Looking for OGRE...
-- OGRE_PREFIX_WATCH changed.
-- Checking for module 'OGRE'
--   Found OGRE, version 1.9.0
-- Found Ogre Ghadamon (1.9.0)
-- Found OGRE: optimized;/usr/lib/x86_64-linux-gnu/libOgreMain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreMain.so
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: optimized;/usr/lib/x86_64-linux-gnu/libOgrePaging.so;debug;/usr/lib/x86_64-linux-gnu/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: optimized;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: optimized;/usr/lib/x86_64-linux-gnu/libOgreProperty.so;debug;/usr/lib/x86_64-linux-gnu/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: optimized;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so;debug;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: optimized;/usr/lib/x86_64-linux-gnu/libOgreVolume.so;debug;/usr/lib/x86_64-linux-gnu/libOgreVolume.so
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: optimized;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so;debug;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so
-- Looking for ignition-math6 -- found version 6.10.0
-- Looking for ignition-transport8 -- found version 8.2.1
-- Searching for dependencies of ignition-transport8
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found suitable version "3.6.1", minimum required is "3") 
-- Config-file not installed for ZeroMQ -- checking for pkg-config
-- Checking for module 'libzmq >= 4'
--   Found libzmq , version 4.3.2
-- Found ZeroMQ: TRUE (Required is at least version "4") 
-- Checking for module 'uuid'
--   Found uuid, version 2.34.0
-- Found UUID: TRUE  
-- Looking for ignition-msgs5 -- found version 5.9.0
-- Searching for dependencies of ignition-msgs5
-- Looking for ignition-math6 -- found version 6.10.0
-- Checking for module 'tinyxml2'
--   Found tinyxml2, version 6.2.0
-- Looking for ignition-msgs5 -- found version 5.9.0
-- Looking for ignition-common3 -- found version 3.14.0
-- Searching for dependencies of ignition-common3
-- Looking for dlfcn.h - found
-- Looking for libdl - found
-- Found DL: TRUE  
-- Searching for <ignition-common3> component [graphics]
-- Looking for ignition-common3-graphics -- found version 3.14.0
-- Searching for dependencies of ignition-common3-graphics
-- Looking for ignition-math6 -- found version 6.10.0
-- Looking for ignition-fuel_tools4 -- found version 4.4.0
-- Searching for dependencies of ignition-fuel_tools4
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.68.0")  
-- Checking for module 'jsoncpp'
--   Found jsoncpp, version 1.7.4
-- Found JSONCPP: TRUE  
-- Checking for module 'libzip'
--   Found libzip, version 1.5.1
-- Found ZIP: TRUE  
-- Looking for ignition-common3 -- found version 3.14.0
-- Looking for ignition-math6 -- found version 6.10.0
-- Looking for ignition-msgs5 -- found version 5.9.0
-- Checking for one of the modules 'glib-2.0'
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- Found OpenCV: /usr (found version "4.2.0") 
-- Found TinyXML: /usr/lib/x86_64-linux-gnu/libtinyxml.so  
-- Checking for module 'gstreamer-1.0 >= 1.0'
--   Found gstreamer-1.0 , version 1.16.3
-- Checking for module 'gstreamer-base-1.0 >= 1.0'
--   Found gstreamer-base-1.0 , version 1.16.3
-- Checking for module 'gstreamer-app-1.0 >= 1.0'
--   Found gstreamer-app-1.0 , version 1.16.3
-- Found GStreamer: GSTREAMER_INCLUDE_DIRS;GSTREAMER_LIBRARIES;GSTREAMER_VERSION;GSTREAMER_BASE_INCLUDE_DIRS;GSTREAMER_BASE_LIBRARIES (Required is at least version "1.0") 
-- Checking for module 'OGRE'
--   Found OGRE, version 1.9.0
-- Building klt_feature_tracker without catkin
-- Building OpticalFlow with OpenCV
-- Found MAVLink: /root/PX4-Autopilot/build/px4_sitl_rtps/mavlink (found version "2.0") 
-- catkin DISABLED
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.6.1") 
-- Checking for module 'protobuf'
--   Found protobuf, version 3.6.1
-- Gazebo version: 11.10
-- Found GStreamer: adding gst_camera_plugin
-- Found GStreamer: adding gst_video_stream_widget
-- Configuring done
-- Generating done
-- Build files have been written to: /root/PX4-Autopilot/build/px4_sitl_rtps/build_gazebo
[7/11] Performing build step for 'sitl_gazebo'
[14/130] Generating /root/PX4-Autopilo...ebo/models/3DR_gps_mag/3DR_gps_mag.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/3DR_gps_mag/3DR_gps_mag.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/3DR_gps_mag/3DR_gps_mag.sdf
[25/130] Generating /root/PX4-Autopilot/Tools/sitl_gazebo/models/c920/c920.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/c920/c920.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/c920/c920.sdf
[26/130] Generating /root/PX4-Autopilot/Tools/sitl_gazebo/models/boat/boat.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/boat/boat.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/boat/boat.sdf
[27/130] Generating /root/PX4-Autopilo...o/models/depth_camera/depth_camera.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/depth_camera/depth_camera.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/depth_camera/depth_camera.sdf
[28/130] Generating /root/PX4-Autopilo..._gazebo/models/cloudship/cloudship.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/cloudship/cloudship.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/cloudship/cloudship.sdf
[29/130] Generating /root/PX4-Autopilot/Tools/sitl_gazebo/models/iris/iris.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/iris/iris.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/iris/iris.sdf
[30/130] Generating /root/PX4-Autopilo...ebo/models/matrice_100/matrice_100.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/matrice_100/matrice_100.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/matrice_100/matrice_100.sdf
[31/130] Generating /root/PX4-Autopilo...models/mb1240-xl-ez4/mb1240-xl-ez4.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/mb1240-xl-ez4/mb1240-xl-ez4.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/mb1240-xl-ez4/mb1240-xl-ez4.sdf
[32/130] Generating /root/PX4-Autopilo...sitl_gazebo/models/pixhawk/pixhawk.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/pixhawk/pixhawk.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/pixhawk/pixhawk.sdf
[34/130] Generating /root/PX4-Autopilot/Tools/sitl_gazebo/models/plane/plane.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/plane/plane.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/plane/plane.sdf
[36/130] Generating /root/PX4-Autopilo...sitl_gazebo/models/px4flow/px4flow.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/px4flow/px4flow.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/px4flow/px4flow.sdf
[37/130] Generating /root/PX4-Autopilot/Tools/sitl_gazebo/models/r200/r200.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/r200/r200.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/r200/r200.sdf
[38/130] Generating /root/PX4-Autopilo...tl_gazebo/models/r1_rover/r1_rover.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/r1_rover/r1_rover.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/r1_rover/r1_rover.sdf
[39/130] Generating /root/PX4-Autopilot/Tools/sitl_gazebo/models/sf10a/sf10a.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/sf10a/sf10a.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/sf10a/sf10a.sdf
[40/130] Generating /root/PX4-Autopilot/Tools/sitl_gazebo/models/rover/rover.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/rover/rover.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/rover/rover.sdf
[41/130] Generating /root/PX4-Autopilo...models/standard_vtol/standard_vtol.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/standard_vtol/standard_vtol.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/standard_vtol/standard_vtol.sdf
[42/130] Generating /root/PX4-Autopilo...azebo/models/tailsitter/tailsitter.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/tailsitter/tailsitter.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/tailsitter/tailsitter.sdf
[44/130] Generating /root/PX4-Autopilo...ndard_vtol_drop/standard_vtol_drop.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/standard_vtol_drop/standard_vtol_drop.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/standard_vtol_drop/standard_vtol_drop.sdf
[47/130] Generating /root/PX4-Autopilo..._gazebo/models/tiltrotor/tiltrotor.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/tiltrotor/tiltrotor.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/tiltrotor/tiltrotor.sdf
[48/130] Generating /root/PX4-Autopilo...o/models/typhoon_h480/typhoon_h480.sdf
/root/PX4-Autopilot/Tools/sitl_gazebo/models/typhoon_h480/typhoon_h480.sdf.jinja -> /root/PX4-Autopilot/Tools/sitl_gazebo/models/typhoon_h480/typhoon_h480.sdf
[102/130] Building CXX object CMakeFil.../gazebo_gimbal_controller_plugin.cpp.o
In file included from /usr/include/string.h:495,
                 from /usr/include/tinyxml.h:42,
                 from /root/PX4-Autopilot/Tools/sitl_gazebo/include/common.h:26,
                 from /root/PX4-Autopilot/Tools/sitl_gazebo/src/gazebo_gimbal_controller_plugin.cpp:18:
In function ‘void* memcpy(void*, const void*, size_t)’,
    inlined from ‘void mav_array_memcpy(void*, const void*, size_t)’ at /root/PX4-Autopilot/build/px4_sitl_rtps/mavlink/development/../protocol.h:176:9,
    inlined from ‘uint16_t mavlink_msg_gimbal_device_information_pack_chan(uint8_t, uint8_t, uint8_t, mavlink_message_t*, uint32_t, const char*, const char*, const char*, uint32_t, uint32_t, uint64_t, uint16_t, uint16_t, float, float, float, float, float, float)’ at /root/PX4-Autopilot/build/px4_sitl_rtps/mavlink/development/../standard/../common/./mavlink_msg_gimbal_device_information.h:209:21,
    inlined from ‘void gazebo::GimbalControllerPlugin::SendGimbalDeviceInformation()’ at /root/PX4-Autopilot/Tools/sitl_gazebo/src/gazebo_gimbal_controller_plugin.cpp:651:50:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:34:33: warning: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ reading 32 bytes from a region of size 4 [-Wstringop-overflow=]
   34 |   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘void* memcpy(void*, const void*, size_t)’,
    inlined from ‘void mav_array_memcpy(void*, const void*, size_t)’ at /root/PX4-Autopilot/build/px4_sitl_rtps/mavlink/development/../protocol.h:176:9,
    inlined from ‘uint16_t mavlink_msg_gimbal_device_information_pack_chan(uint8_t, uint8_t, uint8_t, mavlink_message_t*, uint32_t, const char*, const char*, const char*, uint32_t, uint32_t, uint64_t, uint16_t, uint16_t, float, float, float, float, float, float)’ at /root/PX4-Autopilot/build/px4_sitl_rtps/mavlink/development/../standard/../common/./mavlink_msg_gimbal_device_information.h:210:21,
    inlined from ‘void gazebo::GimbalControllerPlugin::SendGimbalDeviceInformation()’ at /root/PX4-Autopilot/Tools/sitl_gazebo/src/gazebo_gimbal_controller_plugin.cpp:651:50:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:34:33: warning: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ reading 32 bytes from a region of size 12 [-Wstringop-overflow=]
   34 |   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘void* memcpy(void*, const void*, size_t)’,
    inlined from ‘void mav_array_memcpy(void*, const void*, size_t)’ at /root/PX4-Autopilot/build/px4_sitl_rtps/mavlink/development/../protocol.h:176:9,
    inlined from ‘uint16_t mavlink_msg_gimbal_device_information_pack_chan(uint8_t, uint8_t, uint8_t, mavlink_message_t*, uint32_t, const char*, const char*, const char*, uint32_t, uint32_t, uint64_t, uint16_t, uint16_t, float, float, float, float, float, float)’ at /root/PX4-Autopilot/build/px4_sitl_rtps/mavlink/development/../standard/../common/./mavlink_msg_gimbal_device_information.h:211:21,
    inlined from ‘void gazebo::GimbalControllerPlugin::SendGimbalDeviceInformation()’ at /root/PX4-Autopilot/Tools/sitl_gazebo/src/gazebo_gimbal_controller_plugin.cpp:651:50:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:34:33: warning: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ reading 32 bytes from a region of size 1 [-Wstringop-overflow=]
   34 |   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[130/130] Linking CXX shared library libgazebo_user_camera_plugin.so
[10/11] cd /root/PX4-Autopilot/build/p...root/PX4-Autopilot/build/px4_sitl_rtps
SITL ARGS
sitl_bin: /root/PX4-Autopilot/build/px4_sitl_rtps/bin/px4
debugger: none
program: gazebo
model: typhoon_inha
world: grass
src_path: /root/PX4-Autopilot
build_path: /root/PX4-Autopilot/build/px4_sitl_rtps
GAZEBO_PLUGIN_PATH :/root/PX4-Autopilot/build/px4_sitl_rtps/build_gazebo
GAZEBO_MODEL_PATH :/root/PX4-Autopilot/Tools/sitl_gazebo/models
LD_LIBRARY_PATH /usr/lib/x86_64-linux-gnu/gazebo-11/plugins:/opt/ros/galactic/opt/yaml_cpp_vendor/lib:/opt/ros/galactic/lib/x86_64-linux-gnu:/opt/ros/galactic/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/root/PX4-Autopilot/build/px4_sitl_rtps/build_gazebo
Using: /root/PX4-Autopilot/Tools/sitl_gazebo/models/typhoon_inha/typhoon_inha.sdf
gzserver not ready yet, trying again!
No protocol specified
SITL COMMAND: "/root/PX4-Autopilot/build/px4_sitl_rtps/bin/px4" "/root/PX4-Autopilot/build/px4_sitl_rtps"/etc -s etc/init.d-posix/rcS -t "/root/PX4-Autopilot"/test_data
Creating symlink /root/PX4-Autopilot/build/px4_sitl_rtps/etc -> /root/PX4-Autopilot/build/px4_sitl_rtps/tmp/rootfs/etc

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

INFO  [px4] Calling startup script: /bin/sh etc/init.d-posix/rcS 0
INFO  [init] found model autostart file as SYS_AUTOSTART=6013
INFO  [param] selected parameter default file eeprom/parameters_6013
[param] parameter file not found, creating eeprom/parameters_6013
  SYS_AUTOCONFIG: curr: 0 -> new: 1
  SYS_AUTOSTART: curr: 0 -> new: 6013
  CAL_ACC0_ID: curr: 0 -> new: 1310988
  CAL_GYRO0_ID: curr: 0 -> new: 1310988
  CAL_ACC1_ID: curr: 0 -> new: 1310996
  CAL_GYRO1_ID: curr: 0 -> new: 1310996
  CAL_ACC2_ID: curr: 0 -> new: 1311004
  CAL_GYRO2_ID: curr: 0 -> new: 1311004
* CAL_MAG0_ID: curr: 0 -> new: 197388
* CAL_MAG1_ID: curr: 0 -> new: 197644
* SENS_BOARD_X_OFF: curr: 0.0000 -> new: 0.0000
* SENS_DPRES_OFF: curr: 0.0000 -> new: 0.0010
* SYS_AUTOCONFIG: curr: 1 -> new: 0
* IMU_INTEG_RATE: curr: 200 -> new: 250
INFO  [dataman] data manager file './dataman' size is 7866640 bytes
PX4 SIM HOST: localhost
INFO  [simulator] Waiting for simulator to accept connection on TCP port 4560
INFO  [simulator] Simulator connected on TCP port 4560.
INFO  [commander] LED: open /dev/led0 failed (22)
* PWM_AUX_OUT: curr: 0 -> new: 1234
* PWM_MAIN_OUT: curr: 0 -> new: 1234
Gazebo multi-robot simulator, version 11.10.2
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
INFO  [init] Mixer: etc/mixers/hexa_x.main.mix on /dev/pwm_output0
INFO  [init] setting PWM_AUX_OUT none
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 210.117.155.54
[Wrn] [GuiIface.cc:298] Couldn't locate specified .ini. Creating file at "/root/.gazebo/gui.ini"
No protocol specified
[Err] [RenderEngine.cc:749] Can't open display: :0
[Wrn] [RenderEngine.cc:89] Unable to create X window. Rendering will be disabled
[Wrn] [RenderEngine.cc:292] Cannot initialize render engine since render path type is NONE. Ignore this warning ifrendering has been turned off on purpose.
No protocol specified
[Wrn] [GuiIface.cc:120] could not connect to display :0
[Msg] Could not load the Qt platform plugin "xcb" in "" even though it was found.
[Err] [GuiIface.cc:124] This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

INFO  [micrortps_client] UDP transport: ip address: 127.0.0.1; recv port: 2019; send port: 2020
INFO  [micrortps_client] UDP transport: Trying to connect...
INFO  [micrortps_client] UDP transport: Connected to server!
INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 18570 remote port 14550
INFO  [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14580 remote port 14540
INFO  [mavlink] mode: Onboard, data rate: 4000 B/s on udp port 14280 remote port 14030
INFO  [mavlink] mode: Gimbal, data rate: 400000 B/s on udp port 13030 remote port 13280
INFO  [logger] logger started (mode=all)
INFO  [logger] Start file log (type: full)
INFO  [logger] [logger] ./log/2022-09-20/02_12_23.ulg	
INFO  [logger] Opened full log file: ./log/2022-09-20/02_12_23.ulg
INFO  [mavlink] MAVLink only on localhost (set param MAV_{i}_BROADCAST = 1 to enable network)
INFO  [mavlink] MAVLink only on localhost (set param MAV_{i}_BROADCAST = 1 to enable network)
INFO  [px4] Startup script returned successfully
pxh> Exiting NOW.
INFO  [mavlink] partner IP: 127.0.0.1
/root/PX4-Autopilot/Tools/sitl_run.sh: line 251:  1395 Aborted                 (core dumped) nice -n 20 gzclient --verbose $follow_mode  (wd: ~/PX4-Autopilot/build/px4_sitl_rtps/tmp)
/root/PX4-Autopilot/Tools/sitl_run.sh: line 262: kill: (1395) - No such process
FAILED: platforms/posix/CMakeFiles/gazebo_typhoon_inha__grass 
cd /root/PX4-Autopilot/build/px4_sitl_rtps/tmp && /root/PX4-Autopilot/Tools/sitl_run.sh /root/PX4-Autopilot/build/px4_sitl_rtps/bin/px4 none gazebo typhoon_inha grass /root/PX4-Autopilot /root/PX4-Autopilot/build/px4_sitl_rtps
ninja: build stopped: subcommand failed.
make: *** [Makefile:230: px4_sitl_rtps] Error 1
make: Leaving directory '/root/PX4-Autopilot'
/usr/local/bin/entrypoint.sh: line 50: micrortps_agent: command not found
Package 'model_spawn' not found

**Comment by kestr31** [comment]
- There was no problem in image compile process. I tested and there were no problem in Dockerfile in current status.
- However, you are currently experiencing problem in container generation process (Please check an official Docker documentation for this.)

> docker run -it --rm \
> -e DISPLAY=$DISPLAY
> -e QT_NO_MITSHM=1
> -e XDG_RUNTIME_DIR=/tmp
> -v /tmp/.X11-unix:/tmp/.X11-unix
> --net host
> --device=/dev/dri:/dev/dri
> --gpus all
> --privileged
> kestr3l/px4:gazebo-gpu-0.0.2

- On this docker CLI command, there is no statement for user defined command (Such as, bash)
- User defined command is required in running gazebo container since there is no proper `entrypoint.sh` yet
  - This is in to-do list. Currently, please run SITL manually by opening multiple terminals.
  - This can be done by `docker exec -it <CONTAINER_NAME> bash`
  - If you are familiar with settings up powerline fonts, you can also use `zsh` with theme in container.
<br/>

- If you experience additional issues, please make an additional comment. Thank you.
